person:
  name: tcc



spring:

  datasource:
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
      # type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      jdbc:
        template:
          query-timeout: 3

      aop-patterns: configs.*

      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.css,*.png,/druid/*'

      filters: stat,wall,slf4j
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
          enabled: true

        wall:
          enabled: true


        # redis:
        #  database: 0
        # port: 6379
        #host:
        #password:
        #client-type: lettuce
        #lettuce:
        # pool:
        #  max-active: 5




mvc:
    # static-path-pattern: /res/**
  hiddenmethod:
    filter:
      enabled: true

        #resources:
        # static-locations: classpath:/haha


        # url-pattern: /druid/*


mybatis:
    #config-locations: classpath:mybatis/mybatis-configs.xml
    #mapper-locations: classpath:mybatis/mybatis-mapper.xml
  configuration:
    map-underscore-to-camel-case: true


management:

  endpoints:
    enabled-by-default: false

    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

info:
  appName: tcc
  mavenProjectName: @project.artifactId@
